services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterBase\:
    resource: '../Classes/*'

  Brotkrueml\JobRouterBase\Domain\VariableResolvers\JobRouterLanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/jobrouter-language-variable-resolver'
        event: Brotkrueml\JobRouterBase\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterBase\Domain\VariableResolvers\LanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/language-variable-resolver'
        event: Brotkrueml\JobRouterBase\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterBase\Domain\VariableResolvers\LocalisedLabelVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/localised-label-variable-resolver'
        event: Brotkrueml\JobRouterBase\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterBase\Domain\VariableResolvers\TransferIdentifierVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-base/transfer-identifier-variable-resolver'
        event: Brotkrueml\JobRouterBase\Event\ResolveFinisherVariableEvent
